import { createContext, useContext, useState, useCallback } from 'react'

const translations = {
  en: {
    login: {
      welcomeBack: 'Welcome back',
      signInToAccount: 'Sign in to your account',
      emailAddress: 'Email address',
      emailPlaceholder: 'your@email.com',
      password: 'Password',
      signIn: 'Sign In',
      signingIn: 'Signing in...',
      invalidCredentials: 'Invalid credentials',
      platformDescription: 'Field Form Digitalization and AI Validation Platform',
      footer: 'TrackFlow — ONCF Field Operations Platform',
      features: [
        'OCR Form Scanning',
        'AI-Powered Validation',
        'Real-time Notifications',
        'PDF & Excel Reports'
      ],
    },
    nav: {
      dashboard: 'Dashboard',
      forms: 'Forms',
      reports: 'Reports',
      users: 'Users',
      notifications: 'Notifications',
      logout: 'Logout',
    },
    roles: {
      supervisor: 'Encadrant',
      manager: 'Chef de section',
      admin: 'Administrator',
      field_supervisor: 'Encadrant',
      section_head: 'Chef de section',
    },
    common: {
      confirm: 'Confirm',
      cancel: 'Cancel',
      save: 'Save',
      delete: 'Delete',
      edit: 'Edit',
      view: 'View',
      close: 'Close',
      back: 'Back',
      next: 'Next',
      previous: 'Previous',
      search: 'Search',
      filter: 'Filters',
      clear: 'Clear all',
      export: 'Export Excel',
      upload: 'Upload Form',
      loading: 'Loading...',
      noData: 'No data found',
      noResults: 'No results found',
      actions: 'Actions',
      date: 'Date',
      status: 'Status',
      type: 'Type',
    },
    dashboard: {
      welcomeBack: 'Welcome back, {name}',
      subtitle: "Here's what's happening with TrackFlow today.",
      totalForms: 'Total Forms',
      uploadedToday: 'Uploaded Today',
      pendingValidation: 'Pending Validation',
      pendingConfirmation: 'Pending Confirmation',
      confirmedThisMonth: 'Confirmed This Month',
      archivedForms: 'Archived Forms',
      formsByType: 'Forms by Type',
      formsByStatus: 'Forms by Status',
      confirmationSummary: 'Confirmation Summary',
      confirmedToday: 'Confirmed Today',
      confirmedThisWeek: 'Confirmed This Week',
      quickActions: 'Quick Actions',
      generateReport: 'Generate Report',
      reportFormats: 'PDF or Excel',
      formsToday: '{count} forms today',
      formsWaiting: '{count} forms waiting',
    },
    forms: {
      title: 'Forms',
      totalForms: 'total forms',
      uploadForm: 'Upload Form',
      uploadFormScan: 'Upload Form Scan',
      formType: 'Form Type',
      scanFile: 'Scan File',
      clickToSelect: 'Click to select PDF or image',
      uploading: 'Uploading...',
      uploadSuccess: 'Form uploaded! AI validation in progress...',
      uploadFailed: 'Upload failed',
      noFormsFound: 'No forms found',
      tryAdjustingFilters: 'Try adjusting your filters',
      uploadYourFirstForm: 'Upload your first form',
      showing: 'Showing',
      to: 'to',
      of: 'of',
      forms: 'forms',
      page: 'Page',
      uploadedBy: 'Uploaded By',
      exporting: 'Generating export...',
      exportSuccess: 'Export downloaded!',
      exportFailed: 'Export failed',
      statuses: {
        UPLOADED: 'Uploaded',
        OCR_PROCESSING: 'OCR Processing',
        PENDING_VALIDATION: 'Pending Validation',
        PENDING_CONFIRMATION: 'Pending Validation',
        CONFIRMED: 'Validated',
        ARCHIVED: 'Archived',
      },
      types: {
        RAPPORT_M: 'Rapport M',
        LETTRE_SOMMATION_BILLET: 'Sommation Billet',
        LETTRE_SOMMATION_CARTE: 'Sommation Carte',
      },
      filters: {
        allTypes: 'All Types',
        allStatuses: 'All Statuses',
        supervisorName: 'Supervisor name...',
      },
    },
    formDetail: {
      backToForms: 'Back to Forms',
      formId: 'Form ID',
      uploadedBy: 'Uploaded by',
      validatedBy: 'Validated by',
      confirmedBy: 'Confirmed by',
      archive: 'Archive',
      validateForm: 'Validate Form',
      validating: 'Validating...',
      confirmForm: 'Confirm Form',
      confirming: 'Confirming...',
      managerWaitMessage: 'Edit, validate, and archive are available after the supervisor confirms this form.',
      formLockedMessage: 'This form has been validated by the manager and is now locked. You cannot make further edits.',
      formValidatedLocked: 'Form validated by manager (locked)',
      formConfirmedWaiting: 'Form confirmed - waiting for manager validation',
      saveInfractionFirst: 'Save infraction status before confirming',
      confirmAfterValidation: 'Confirm available after AI validation',
      formFields: 'Form Fields',
      aiValidation: 'AI Validation',
      extractedFields: 'Extracted Fields',
      editFields: 'Edit Fields',
      addField: 'Add Field',
      saveChanges: 'Save Changes',
      saving: 'Saving...',
      field: 'Field',
      extractedValue: 'Extracted Value',
      confirmedValue: 'Confirmed Value',
      status: 'Status',
      notExtracted: 'Not extracted',
      extraField: 'Extra field',
      addMissingField: 'Add Missing Field',
      fieldName: 'Field Name',
      selectField: 'Select field...',
      value: 'Value',
      enterValue: 'Enter value...',
      aiValidationResults: 'AI Validation Results',
      noValidation: 'No validation found.',
      suggestions: 'suggestion(s)',
      noErrors: 'No errors found — form looks good!',
      extracted: 'Extracted',
      suggested: 'Suggested',
      confidence: 'Confidence',
      accept: 'Accept',
      reject: 'Reject',
      override: 'Override',
      overrideValue: 'Override value...',
      infractionStatus: "Statut de l'infraction",
      statut: 'Statut',
      gareReglement: 'Gare de Réglement',
      numPP: 'N° PP',
      montantRegle: 'Montant Réglé',
      montantRegleMAD: 'Montant Réglé (MAD)',
      montantPlaceholder: 'Ex: 150',
      numPPRegularisation: 'N° PP de Régularisation',
      numPPPlaceholder: 'Ex: PP-2026-001',
      regularisee: 'Régularisée',
      nonRegularisee: 'Non Régularisée',
      select: 'Sélectionner...',
      selectGare: 'Sélectionner une gare...',
      modify: 'Modify',
      saveInfractionStatus: 'Save Infraction Status',
      suggestion: 'Suggestion',
      decisionFailed: 'Failed to save decision',
      confirmSuccess: 'Form confirmed successfully!',
      confirmFailed: 'Failed to confirm form',
      archiveSuccess: 'Form archived!',
      archiveFailed: 'Failed to archive form',
      infractionSaved: 'Infraction status saved!',
      infractionFailed: 'Failed to save infraction status',
      validateSuccess: 'Form validated. The supervisor has been notified.',
      validateFailed: 'Failed to validate form',
      fieldsUpdated: 'Fields updated successfully!',
      fieldsUpdatedManager: 'Fields updated. The supervisor has been notified.',
      fieldsUpdateFailed: 'Failed to update fields',
      fieldAdded: 'Field added successfully',
      fieldAddFailed: 'Failed to add field',
      confirmFormMessage: 'Are you sure you want to confirm this form? This action cannot be undone.',
      yesConfirm: 'Yes, Confirm',
      archiveForm: 'Archive Form',
      archiveFormMessage: 'Are you sure you want to archive this form?',
      decisionConfirmMessage: 'Are you sure you want to {decision} this suggestion?',
      validationStatus: {
        COMPLETED: 'Completed',
        PENDING: 'Pending',
        PROCESSING: 'Processing',
        FAILED: 'Failed',
      },
      decisionStatus: {
        PENDING: 'Pending',
        ACCEPTED: 'Accepted',
        REJECTED: 'Rejected',
        OVERRIDDEN: 'Overridden',
      },
    },
    notifications: {
      title: 'Notifications',
      unread: 'unread',
      markAllAsRead: 'Mark all as read',
      noNotifications: 'No notifications yet.',
      loading: 'Loading notifications...',
      viewForm: 'View form',
      markAsRead: 'Mark as read',
    },
    users: {
      title: 'User Management',
      administration: 'ONCF Administration',
      description: 'Manage field supervisors, managers, and administrators across TrackFlow operations.',
      newUser: 'New User',
      createUser: 'Create User',
      creating: 'Creating...',
      changeRole: 'Change Role',
      updateRole: 'Update Role',
      resetPassword: 'Reset Password',
      deactivateUser: 'Deactivate User',
      activateUser: 'Activate User',
      deactivate: 'Deactivate',
      activate: 'Activate',
      createSuccess: 'User created successfully!',
      createFailed: 'Failed to create user',
      roleUpdateSuccess: 'Role updated successfully!',
      roleUpdateFailed: 'Failed to update role',
      statusUpdateSuccess: 'User status updated!',
      statusUpdateFailed: 'Failed to update status',
      passwordResetSuccess: 'Password reset successfully!',
      passwordResetFailed: 'Failed to reset password',
      changingRoleFor: 'Changing role for',
      resettingPasswordFor: 'Reset password for',
      noUsersFound: 'No users found',
      adjustFilters: 'Adjust the search or filters to find the account you need.',
      searchPlaceholder: 'Search by name, email, or role',
      openActions: 'Open actions for {name}',
      deactivateConfirm: 'Are you sure you want to deactivate {name}? They will no longer be able to login.',
      activateConfirm: 'Activate {name}\'s account?',
      stats: {
        totalUsers: 'Total Users',
        active: 'Active',
        inactive: 'Inactive',
        admins: 'Admins',
      },
      filters: {
        allRoles: 'All roles',
        allStatuses: 'All statuses',
        administrators: 'Administrators',
        managers: 'Managers',
        supervisors: 'Field supervisors',
        activeOnly: 'Active only',
        inactiveOnly: 'Inactive only',
      },
      table: {
        user: 'User',
        email: 'Email',
        role: 'Role',
        status: 'Status',
        actions: 'Actions',
      },
      status: {
        active: 'Active',
        inactive: 'Inactive',
      },
      form: {
        fullName: 'Full Name',
        email: 'Email',
        role: 'Role',
        newRole: 'New role',
        selectRole: 'Select role...',
        newPassword: 'New password',
        enterPassword: 'Enter a secure password',
      },
      actions: {
        changeRole: 'Change Role',
        activate: 'Activate',
        deactivate: 'Deactivate',
        resetPassword: 'Reset Password',
      },
    },
    confirmDialog: {
      confirm: 'Confirm',
      cancel: 'Cancel',
    },
  },
  fr: {
    login: {
      welcomeBack: 'Bon retour',
      signInToAccount: 'Connectez-vous à votre compte',
      emailAddress: 'Adresse email',
      emailPlaceholder: 'votre@email.com',
      password: 'Mot de passe',
      signIn: 'Se connecter',
      signingIn: 'Connexion...',
      invalidCredentials: 'Identifiants invalides',
      platformDescription: 'Plateforme de digitalisation des formulaires terrain et de validation par IA',
      footer: 'TrackFlow — Plateforme des opérations terrain ONCF',
      features: [
        'Numérisation OCR des formulaires',
        'Validation par IA',
        'Notifications en temps réel',
        'Rapports PDF & Excel'
      ],
    },
    nav: {
      dashboard: 'Tableau de bord',
      forms: 'Formulaires',
      reports: 'Rapports',
      users: 'Utilisateurs',
      notifications: 'Notifications',
      logout: 'Déconnexion',
    },
    roles: {
      supervisor: 'Encadrant',
      manager: 'Chef de section',
      admin: 'Administrateur',
      field_supervisor: 'Encadrant',
      section_head: 'Chef de section',
    },
    common: {
      confirm: 'Confirmer',
      cancel: 'Annuler',
      save: 'Enregistrer',
      delete: 'Supprimer',
      edit: 'Modifier',
      view: 'Voir',
      close: 'Fermer',
      back: 'Retour',
      next: 'Suivant',
      previous: 'Précédent',
      search: 'Rechercher',
      filter: 'Filtres',
      clear: 'Tout effacer',
      export: 'Exporter Excel',
      upload: 'Télécharger un formulaire',
      loading: 'Chargement...',
      noData: 'Aucune donnée trouvée',
      noResults: 'Aucun résultat trouvé',
      actions: 'Actions',
      date: 'Date',
      status: 'Statut',
      type: 'Type',
    },
    dashboard: {
      welcomeBack: 'Bon retour, {name}',
      subtitle: 'Voici ce qui se passe sur TrackFlow aujourd\'hui.',
      totalForms: 'Total formulaires',
      uploadedToday: 'Téléchargés aujourd\'hui',
      pendingValidation: 'En attente de validation',
      pendingConfirmation: 'En attente de confirmation',
      confirmedThisMonth: 'Confirmés ce mois',
      archivedForms: 'Formulaires archivés',
      formsByType: 'Formulaires par type',
      formsByStatus: 'Formulaires par statut',
      confirmationSummary: 'Résumé des confirmations',
      confirmedToday: 'Confirmés aujourd\'hui',
      confirmedThisWeek: 'Confirmés cette semaine',
      quickActions: 'Actions rapides',
      generateReport: 'Générer un rapport',
      reportFormats: 'PDF ou Excel',
      formsToday: '{count} formulaires aujourd\'hui',
      formsWaiting: '{count} formulaires en attente',
    },
    forms: {
      title: 'Formulaires',
      totalForms: 'formulaires au total',
      uploadForm: 'Télécharger un formulaire',
      uploadFormScan: 'Télécharger un formulaire scanné',
      formType: 'Type de formulaire',
      scanFile: 'Fichier scanné',
      clickToSelect: 'Cliquez pour sélectionner un PDF ou une image',
      uploading: 'Téléchargement...',
      uploadSuccess: 'Formulaire téléchargé ! Validation IA en cours...',
      uploadFailed: 'Échec du téléchargement',
      noFormsFound: 'Aucun formulaire trouvé',
      tryAdjustingFilters: 'Essayez d\'ajuster vos filtres',
      uploadYourFirstForm: 'Téléchargez votre premier formulaire',
      showing: 'Affichage',
      to: 'à',
      of: 'sur',
      forms: 'formulaires',
      page: 'Page',
      uploadedBy: 'Téléchargé par',
      exporting: 'Génération de l\'export...',
      exportSuccess: 'Export téléchargé !',
      exportFailed: 'Échec de l\'export',
      statuses: {
        UPLOADED: 'Téléchargé',
        OCR_PROCESSING: 'Traitement OCR',
        PENDING_VALIDATION: 'En attente de validation',
        PENDING_CONFIRMATION: 'En attente de validation',
        CONFIRMED: 'Validé',
        ARCHIVED: 'Archivé',
      },
      types: {
        RAPPORT_M: 'Rapport M',
        LETTRE_SOMMATION_BILLET: 'Sommation Billet',
        LETTRE_SOMMATION_CARTE: 'Sommation Carte',
      },
      filters: {
        allTypes: 'Tous les types',
        allStatuses: 'Tous les statuts',
        supervisorName: 'Nom de l\'encadrant...',
      },
    },
    formDetail: {
      backToForms: 'Retour aux formulaires',
      formId: 'ID Formulaire',
      uploadedBy: 'Téléchargé par',
      validatedBy: 'Validé par',
      confirmedBy: 'Confirmé par',
      archive: 'Archiver',
      validateForm: 'Valider le formulaire',
      validating: 'Validation...',
      confirmForm: 'Confirmer le formulaire',
      confirming: 'Confirmation...',
      managerWaitMessage: 'La modification, la validation et l\'archivage sont disponibles après que l\'encadrant a confirmé ce formulaire.',
      formLockedMessage: 'Ce formulaire a été validé par le chef de section et est maintenant verrouillé. Vous ne pouvez plus le modifier.',
      formValidatedLocked: 'Formulaire validé par le chef de section (verrouillé)',
      formConfirmedWaiting: 'Formulaire confirmé - en attente de validation du chef de section',
      saveInfractionFirst: 'Enregistrez le statut de l\'infraction avant de confirmer',
      confirmAfterValidation: 'Confirmation disponible après validation IA',
      formFields: 'Champs du formulaire',
      aiValidation: 'Validation IA',
      extractedFields: 'Champs extraits',
      editFields: 'Modifier les champs',
      addField: 'Ajouter un champ',
      saveChanges: 'Enregistrer les modifications',
      saving: 'Enregistrement...',
      field: 'Champ',
      extractedValue: 'Valeur extraite',
      confirmedValue: 'Valeur confirmée',
      status: 'Statut',
      notExtracted: 'Non extrait',
      extraField: 'Champ supplémentaire',
      addMissingField: 'Ajouter un champ manquant',
      fieldName: 'Nom du champ',
      selectField: 'Sélectionner un champ...',
      value: 'Valeur',
      enterValue: 'Entrer une valeur...',
      aiValidationResults: 'Résultats de la validation IA',
      noValidation: 'Aucune validation trouvée.',
      suggestions: 'suggestion(s)',
      noErrors: 'Aucune erreur trouvée — le formulaire semble correct !',
      extracted: 'Extrait',
      suggested: 'Suggéré',
      confidence: 'Confiance',
      accept: 'Accepter',
      reject: 'Refuser',
      override: 'Remplacer',
      overrideValue: 'Valeur de remplacement...',
      infractionStatus: "Statut de l'infraction",
      statut: 'Statut',
      gareReglement: 'Gare de Réglement',
      numPP: 'N° PP',
      montantRegle: 'Montant Réglé',
      montantRegleMAD: 'Montant Réglé (MAD)',
      montantPlaceholder: 'Ex: 150',
      numPPRegularisation: 'N° PP de Régularisation',
      numPPPlaceholder: 'Ex: PP-2026-001',
      regularisee: 'Régularisée',
      nonRegularisee: 'Non Régularisée',
      select: 'Sélectionner...',
      selectGare: 'Sélectionner une gare...',
      modify: 'Modifier',
      saveInfractionStatus: 'Enregistrer le statut de l\'infraction',
      suggestion: 'Suggestion',
      decisionFailed: 'Échec de l\'enregistrement de la décision',
      confirmSuccess: 'Formulaire confirmé avec succès !',
      confirmFailed: 'Échec de la confirmation du formulaire',
      archiveSuccess: 'Formulaire archivé !',
      archiveFailed: 'Échec de l\'archivage du formulaire',
      infractionSaved: 'Statut de l\'infraction enregistré !',
      infractionFailed: 'Échec de l\'enregistrement du statut de l\'infraction',
      validateSuccess: 'Formulaire validé. L\'encadrant a été notifié.',
      validateFailed: 'Échec de la validation du formulaire',
      fieldsUpdated: 'Champs mis à jour avec succès !',
      fieldsUpdatedManager: 'Champs mis à jour. L\'encadrant a été notifié.',
      fieldsUpdateFailed: 'Échec de la mise à jour des champs',
      fieldAdded: 'Champ ajouté avec succès',
      fieldAddFailed: 'Échec de l\'ajout du champ',
      confirmFormMessage: 'Êtes-vous sûr de vouloir confirmer ce formulaire ? Cette action ne peut pas être annulée.',
      yesConfirm: 'Oui, confirmer',
      archiveForm: 'Archiver le formulaire',
      archiveFormMessage: 'Êtes-vous sûr de vouloir archiver ce formulaire ?',
      decisionConfirmMessage: 'Êtes-vous sûr de vouloir {decision} cette suggestion ?',
      validationStatus: {
        COMPLETED: 'Terminée',
        PENDING: 'En attente',
        PROCESSING: 'En cours',
        FAILED: 'Échouée',
      },
      decisionStatus: {
        PENDING: 'En attente',
        ACCEPTED: 'Acceptée',
        REJECTED: 'Refusée',
        OVERRIDDEN: 'Remplacée',
      },
    },
    notifications: {
      title: 'Notifications',
      unread: 'non lues',
      markAllAsRead: 'Tout marquer comme lu',
      noNotifications: 'Aucune notification pour le moment.',
      loading: 'Chargement des notifications...',
      viewForm: 'Voir le formulaire',
      markAsRead: 'Marquer comme lu',
    },
    users: {
      title: 'Gestion des utilisateurs',
      administration: 'Administration ONCF',
      description: 'Gérez les encadrants, chefs de section et administrateurs des opérations TrackFlow.',
      newUser: 'Nouvel utilisateur',
      createUser: 'Créer un utilisateur',
      creating: 'Création...',
      changeRole: 'Changer le rôle',
      updateRole: 'Mettre à jour le rôle',
      resetPassword: 'Réinitialiser le mot de passe',
      deactivateUser: 'Désactiver l\'utilisateur',
      activateUser: 'Activer l\'utilisateur',
      deactivate: 'Désactiver',
      activate: 'Activer',
      createSuccess: 'Utilisateur créé avec succès !',
      createFailed: 'Échec de la création de l\'utilisateur',
      roleUpdateSuccess: 'Rôle mis à jour avec succès !',
      roleUpdateFailed: 'Échec de la mise à jour du rôle',
      statusUpdateSuccess: 'Statut de l\'utilisateur mis à jour !',
      statusUpdateFailed: 'Échec de la mise à jour du statut',
      passwordResetSuccess: 'Mot de passe réinitialisé avec succès !',
      passwordResetFailed: 'Échec de la réinitialisation du mot de passe',
      changingRoleFor: 'Changement de rôle pour',
      resettingPasswordFor: 'Réinitialiser le mot de passe pour',
      noUsersFound: 'Aucun utilisateur trouvé',
      adjustFilters: 'Ajustez la recherche ou les filtres pour trouver le compte souhaité.',
      searchPlaceholder: 'Rechercher par nom, email ou rôle',
      openActions: 'Ouvrir les actions pour {name}',
      deactivateConfirm: 'Êtes-vous sûr de vouloir désactiver {name} ? Il ne pourra plus se connecter.',
      activateConfirm: 'Activer le compte de {name} ?',
      stats: {
        totalUsers: 'Total utilisateurs',
        active: 'Actifs',
        inactive: 'Inactifs',
        admins: 'Admins',
      },
      filters: {
        allRoles: 'Tous les rôles',
        allStatuses: 'Tous les statuts',
        administrators: 'Administrateurs',
        managers: 'Chefs de section',
        supervisors: 'Encadrants',
        activeOnly: 'Actifs uniquement',
        inactiveOnly: 'Inactifs uniquement',
      },
      table: {
        user: 'Utilisateur',
        email: 'Email',
        role: 'Rôle',
        status: 'Statut',
        actions: 'Actions',
      },
      status: {
        active: 'Actif',
        inactive: 'Inactif',
      },
      form: {
        fullName: 'Nom complet',
        email: 'Email',
        role: 'Rôle',
        newRole: 'Nouveau rôle',
        selectRole: 'Sélectionner un rôle...',
        newPassword: 'Nouveau mot de passe',
        enterPassword: 'Entrez un mot de passe sécurisé',
      },
      actions: {
        changeRole: 'Changer le rôle',
        activate: 'Activer',
        deactivate: 'Désactiver',
        resetPassword: 'Réinitialiser le mot de passe',
      },
    },
    confirmDialog: {
      confirm: 'Confirmer',
      cancel: 'Annuler',
    },
  },
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'fr'
  })

  const toggleLanguage = useCallback(() => {
    setLanguage(prev => {
      const newLang = prev === 'en' ? 'fr' : 'en'
      localStorage.setItem('language', newLang)
      return newLang
    })
  }, [])

  const t = useCallback((path, params = {}) => {
    const keys = path.split('.')
    let value = translations[language]
    
    for (const key of keys) {
      value = value?.[key]
    }
    
    if (typeof value === 'string' && params) {
      Object.entries(params).forEach(([key, val]) => {
        value = value.replace(`{${key}}`, val)
      })
    }
    
    return value || path
  }, [language])

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}